[package]
name = "autospy"
version = "0.0.2"
edition = "2024"
description = "A test spy object library."
license = "MIT"
repository = "https://github.com/lhalf/autospy"
documentation = "https://docs.rs/autospy"
keywords = ["mock", "testing", "spy", "mocking", "fake"]
categories = ["development-tools::testing"]
readme = "README.md"
exclude = ["/tests/", "justfile"]

[workspace]
members = ["autospy_macro"]

[dependencies]
autospy_macro = { path = "autospy_macro", version = "0.0.2" }
