[package]
name = "autospy"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = { version = "*", default-features = false }
syn = { version = "*", default-features = false, features = ["parsing", "proc-macro", "full"] }
proc-macro2 = { version = "*", default-features = false }